name: Release Product
permissions:
  write-all

on:
  pull_request:
    branches:
      - "main"
      - "RN"
    types:
      - closed
    paths-ignore:
      - 'image/**'
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch: {}

env:
  VERSION_MAJOR: 2
  VERSION_MINOR: 3
  VERSION_REV_OFFSET: 166
  RELEASE_VER: ''
  PACKAGE_NAME: ''
  IS_PRERELEASE: false
  VCPKG_TOOL_FOLDER: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg'

jobs:
  build-and-release:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true)
    runs-on: windows-2022
    env:
      CONFIGURATION: FinalAlertRelease YR
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive
        lfs: true

    - uses: ./.github/actions/setup-msvc-vcpkg
      id: vcpkg
      with:
        arch: x64
        vcpkg-root: ${{ env.VCPKG_TOOL_FOLDER }}
        
    - name: build-msvc
      run: |
        MSBuild MissionEditor.sln /m /p:Configuration="${{ env.CONFIGURATION }}" /p:Platform=x64 /t:MissionEditor

    - name: Handle version
      shell: bash
      run: |
        revNum=$((${{ github.run_number }} - ${{ env.VERSION_REV_OFFSET }}))
        versionNum=${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}.$revNum
        pkgName=FinalRevenge-v$versionNum.zip
        ./scripts/update_product_version.ps1 -major ${{ env.VERSION_MAJOR }} -minor ${{ env.VERSION_MINOR }} -revision $revNum
        echo "RELEASE_VER=$versionNum" >> $GITHUB_ENV
        echo "PACKAGE_NAME=$pkgName" >> $GITHUB_ENV

    - name: Pack up
      shell: pwsh
      run: |
        cd dist/FinalRevenge
        Compress-Archive -Path ./* -DestinationPath ../${{ env.PACKAGE_NAME }}
    - name: Release - ${{ env.RELEASE_VER }}
      
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_VER }}
        name: ${{ env.RELEASE_VER }}
        files: dist/${{ env.PACKAGE_NAME }}
        target_commitish: ${{ github.ref }}
        prerelease: ${{ env.IS_PRERELEASE }}
