name: Basic verify

on:
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
    branches:
      - "**"
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'image/**'
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:

env:
  VCPKG_TOOL_FOLDER: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg'

jobs:
  compile-check:
    runs-on: windows-2022
    env:
      CONFIGURATION: FinalAlertDebug YR
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive
        lfs: true

    - uses: ./.github/actions/setup-msvc-vcpkg
      id: vcpkg
      with:
        arch: x64
        vcpkg-root: ${{ env.VCPKG_TOOL_FOLDER }}

    - name: Build Main Program (MSVC)
      run: |
        MSBuild MissionEditor.sln /m /p:Configuration="${{ env.CONFIGURATION }}" /p:Platform=x64 /t:MissionEditor

    - name: Build UT tool (MSVC)
      env:
        VCPKG_ENABLE_MANIFEST: "0"
      run: |
        MSBuild MissionEditor.sln /m /p:Configuration="${{ env.CONFIGURATION }}" /p:Platform=x64 /t:UnitTest

    - name: do UT
      run: |
        cd x64\Debug
        ./UnitTest

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FinalRevenge-pr-${{ github.run_number }}
        path: dist/FinalRevenge
        retention-days: 7
